name: "Release Version"
on:
  push:
    branches:
      - main
jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.versioning.outputs.version_tag }}
      current_commit: ${{ steps.versioning.outputs.current_commit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Versioning
        id: versioning
        uses: paulhatch/semantic-version@v5.0.2
  generate-release-notes:
    runs-on: ubuntu-latest
    needs: bump-version
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate release notes
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ needs.bump-version.outputs.version_tag }}
          commit: ${{ needs.bump-version.outputs.current_commit }}
