# Workflow name
name: "Build"

# Event for the workflow
on: push

# List of jobs
jobs:
  release:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Release
        run: npm run release
