name: "Release Version"
on:
  push:
    branches:
      - main
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Versioning
        uses: paulhatch/semantic-version@v5.0.2
