name: "Release Version"
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.versioning.outputs.version_tag }}
      current_commit: ${{ steps.versioning.outputs.current_commit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Versioning
        id: versioning
        uses: paulhatch/semantic-version@v5.0.2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Update version in package.json
        run: |
          new_version=${{ steps.versioning.outputs.version_tag }}
          # Update the version in package.json
          npm version --no-git-tag-version $new_version
      - name: Commit and push changes
        run: |
          git config user.name "Amin Roslan"
          git config user.email "amnrsln@gmail.com"
          git add package.json
          git commit -m "Bump version to $new_version"
          git push
  generate-release-notes:
    runs-on: ubuntu-latest
    needs: bump-version
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate release notes
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ needs.bump-version.outputs.version_tag }}
          commit: ${{ needs.bump-version.outputs.current_commit }}
  publish-to-npm:
    runs-on: ubuntu-latest
    needs: generate-release-notes
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
